FLASK/Flask-sql/models/user.py
from extensions import db

class User(db.Model):
    ___tablename__ = "users"
    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(80),nullable = False, unique = False)
    email = db.Column(db.String(200),nullable = False, unique = True)
    password = db.Column(db.String(200))
    created_at = db.Column(db.DateTime(),nullable = False, server_default = db.func.now())
    updated_at = db.Column(db.DateTime(),nullable = False, server_default = db.func.now(),onupdate = db.func.now())

    @property
    def data(self):
        return{
            'id' : self.id,
            'name' : self.name,
            'email' : self.email,
            'password' : self.password
        }
    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_all(cls):
        r=cls.query.all()
        result=[]
        
        for i in r:
            result.append(i.data)
        return result
    
    
    @classmethod
    def get_by_id(cls,id):
        return cls.query.filter(cls.id==id).first()

FLASK/Flask-sql/app.py
from flask import Flask;
from config import Config
from extensions import db
from flask_migrate import Migrate
from routes import main

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    register_resource(app)
    register_extensions(app)
    return app

def register_extensions(app):
    db.init_app(app)
    migrate = Migrate(app,db)

def register_resource(app):

    app.register_blueprint(main)


if __name__ == "__main__":
    app = create_app()
    app.run('127.0.0.1',5000)

FLASK/Flask-sql/controllers/user.py
from flask import request
from models.user import User
from extensions import db

def add_user_function():
    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        password = request.form['password']
        user = User(
            name = name,
            email = email,
            password = password
        )

        user.save()
        data = {
            'id' : user.id,
            'name' : user.name,
            'email' : user.email,
            'password' : user.password
            
        }
        return data
    
def edit_user_function(data):
       if request.method == 'POST':
        data.name = request.form['name']
        data.email = request.form['email']
        data.password = request.form['password']
        
        
        
        db.session.commit()
        return data
    
    

def delete_user_function(user):
    db.session.delete(user)
    db.session.commit()
    

FLASK/Flask-sql/routes.py
from flask import Blueprint,render_template,redirect,url_for;
from controllers.user import add_user_function,edit_user_function,delete_user_function;
import sys
from models.user import User;
main = Blueprint('main',__name__)

@main.route('/', methods = ['GET'])
def home():
    data=User.get_all()
    return render_template("index.html",data=data)

@main.route('/adduser', methods = ['GET','POST'])
def add_user():
    data = add_user_function()
    print(data,file = sys.stderr)
    return render_template("adduser.html",data = data)

@main.route('/edituser/<int:id>', methods = ['GET','POST'])
def edit_user(id):
    user=User.get_by_id(id)
    data=edit_user_function(user)
    return render_template("edituser.html",user=user,data=data)


@main.route("/deleteuser/<int:id>",methods=["POST"])
def delete_user(id):
    user=User.get_by_id(id)
    print(user,file = sys.stderr)
    delete_user_function(user)
    return redirect(url_for("main.home"))

FLASK/Flask-sql/templates/adduser.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center h-100">
            <div class="col-lg-8 col-xl-6">
                <nav>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Back to home</a></li>
                    </ol>
                </nav>
                <div class="card rounded-3">
                    <div class="card-body p-4 p-nd-5">
                        <h2 class="mb-4 pb-2 pd-nd-0 np-nd-2 px-md-2 text-center">Add user</h2>
                        <form method="POST" action="/adduser">
                            <div class="form-group">
                                <input type="text" id="name" name="name" class="form-control" placeholder="Name" /><br/>

                            </div>
                            <div class="form-group">
                                <input type="email" id="email" name="email" class="form-control" placeholder="Email" /><br/>

                            </div>
                            <div class="form-group">
                                <input type="password" id="password" name="password" class="form-control" placeholder="Password" /><br/>

                            </div>
                            <br/>
                            <br/>
                            <input type="submit" value="submit" class="btn btn-success text-center">
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>

FLASK/Flask-sql/templates/edituser.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center h-100">
            <div class="col-lg-8 col-xl-6">
                <nav>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Back to home</a></li>
                    </ol>
                </nav>
                <div class="card rounded-3">
                    <div class="card-body p-4 p-nd-5">
                        <h2 class="mb-4 pb-2 pd-nd-0 np-nd-2 px-md-2 text-center">Edit user</h2>
                        <form method="POST" action="/edituser">
                            <div class="form-group">
                                <input type="text" id="name" name="name" class="form-control" placeholder={{user.name}} /><br/>

                            </div>
                            <div class="form-group">
                                <input type="email" id="email" name="email" class="form-control" placeholder={{user.email}}  /><br/>

                            </div>
                            <div class="form-group">
                                <input type="password" id="password" name="password" class="form-control" placeholder={{user.password}}  /><br/>

                            </div>
                            <br/>
                            <br/>
                            <input type="submit" class="btn btn-success text-center">
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>

FLASK/Flask-sql/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script>
      function confirmDelete(user_id){
var confirmation=confirm("Are you sure you want to delete this user?")
if (confirmation){
  var form =document.createElement("form");
  form.method="POST";
  form.action="/deleteuser/"+user_id;
  document.body.appendChild(form);
  form.submit();

}
      }
    </script>
</head>

<body>
    <div class="my-5 text-center">
<button type="button" class="btn btn-primary">
    <a  class="text-white" href="{{url_for('main.add_user')}}" >Add User</a>
</button>
<br/>
<div class="w-70 d-flex p-5">
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {%for item in data %}

          <tr>
            <th scope="row">{{item.id}}</th>
            <td>{{item.name}}</td>
            <td>{{item.email}}</td>
            <td>
                <a href="/edituser/{{item.id}}"><button class="btn btn-success">Edit</button></a>  |
                <button class="btn btn-danger" type="button" onclick="confirmDelete(`{{item.id}}`)">Delete</button>
            </td>
          </tr>
          {%endfor%}

          
        </tbody>
      </table>
</div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>